#!/bin/bash

echo "Checking and installing required PIP packages"

PKG_OK=$(sudo -H pip3 freeze| grep -i "pillow==")
echo Checking for pillow: $PKG_OK
if [ "" == "$PKG_OK" ]; then
    echo "No pillow. Setting up pillow."
    sudo -H pip3 install pillow
fi

exit 0
